### ISSUE TITLE
Feature request: Lazy Values

### ISSUE THREAD

**Issue by andreisobchuck** [twineworks/tweakflow#1]
A context for a user script (variables that could be provided by an application) in an application could have high cost to calculate. But the script could be dependent only on few provided variables. We do not see a way to provide only that values that required in a script. 

It would be greate feature to add a way to request a value for a variable from tweakflow runtime to host application. It could be like VariableResolver in MVEL or just a function per variable. Or it could be  just ability to get list of dependent variables that referenced from a script.

**Comment by slawo-ch** [comment]
Thanks for the feature request. You're right, there should be a way to 
avoid providing expensive values until they are needed.

I'm planning on exposing dependency information, as well as allowing lazy 
evaluation. Expect an update next week.

As a stopgap you could provide a function that users call, instead of the 
computed value.

Best
Slawo

**Comment by slawo-ch** [comment]
Just pushed the ability to check whether a provided variable is referenced to master. A small example class is included. Will update docs and push a release early next week.

I've decided to expose dependency information on a `Runtime.Var` as a simple boolean flag. 

You can check all provided variables to see whether they are relevant or not. I could not think of a use case where lazy evaluation in the form of delayed execution through a function or class would be preferable, so I left it out.

**Comment by slawo-ch** [comment]
Added `isReferenced()` call to Runtime.Vars. [Example](https://github.com/twineworks/tweakflow/blob/releases/0.0.7/src/main/java/com/twineworks/tweakflow/examples/LazilyProvidedVars.java) included.
