### ISSUE TITLE
Symbol strings with numeric chars as first character

### ISSUE THREAD

**Issue by gabrielbauman** [twineworks/tweakflow#5]
Hi again, 

I'm using tweakflow to map keys across third-party stores and would like to use the symbol string format so as not to have so many quotes everywhere. Unfortunately some of the keys have numeric chars as their first character.

Is there any reason not to allow symbol strings such as `:1twothree`?

**Comment by slawo-ch** [comment]
Good question, let me look into that. I'll double-check if the `:` symbol and digits clash somehow semantically.

**Comment by slawo-ch** [comment]
Released as part of [0.13.0](https://github.com/twineworks/tweakflow/releases/tag/releases%2F0.13.0)

Thanks for using Tweakflow!
